version: '3.8'

services:
  ppe-detection:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./runs:/app/runs
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
