apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppe-detection
  labels:
    app: ppe-detection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ppe-detection
  template:
    metadata:
      labels:
        app: ppe-detection
    spec:
      containers:
      - name: ppe-detection
        image: ppe-detection:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: MODEL_PATH
          value: "ppe_quick_finetune/yolov8n_ppe_20epochs/weights/best.pt"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ppe-detection-service
spec:
  selector:
    app: ppe-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ppe-detection-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ppe-detection.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ppe-detection-service
            port:
              number: 80
